server:
  port: 8081
spring:
  application:
    name: demo
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=UTF-8
    username: root
    password: ok
    driver-class-name: com.mysql.jdbc.Driver


  redis:
    host: localhost
    port: 6379
    password:
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 500
          min-idle: 0
      letture:
        shutdown-timeout: 0